#!/bin/bash
if [ ! -d ./node_modules ]; then
    echo "No node_modules ... installing Prettier.io" > /dev/stderr
    npm install --save-dev --save-exact prettier
    npm install --save-dev --save-exact prettier-plugin-java
fi


PRETTIER_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.jsx" "*.ts" "*.tsx" "*.json" "*.yaml" "*.md" "*.html" "*.css" "*.java"| sed 's| |\\ |g')

if [ -n "$PRETTIER_FILES" ]; then

    # Prettify all selected files
    echo "$PRETTIER_FILES" | xargs ./node_modules/.bin/prettier --write

    # Add back the modified/prettified files to staging
    echo "$PRETTIER_FILES" | xargs git add
fi

BLACK_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.py" "*.pyi"| sed 's| |\\ |g')

if [ -n "$BLACK_FILES" ]; then

    if ! command -v black  &> /dev/null; then
        echo "Please 'pip install black' before committing python files" > /dev/stderr
        exit 22
    fi

    # Run black on all selected files
    echo "$BLACK_FILES" | xargs black --line-length 80

    # Add the potentially modified files to staging
    echo "$BLACK_FILES" | xargs git add
fi

exit 0
